version: "3.9"

services:
  flask_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - /etc/signup-bot/.env
    restart: always

  discord_bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
      - /etc/signup-bot/.env
    restart: always
    depends_on:
      - flask_api